### PR TITLE
fix jruby 9.3+ compatibility

### LINKED ISSUE #11: JRuby 9.3 Compatibility
For some reason, Xorcist.xor! is not being required properly when importing the JAR.

https://github.com/fny/xorcist/runs/7636403550?check_suite_focus=true

I've reached out to the JRuby team: jruby/jruby#7287

### PR DESCRIPTION
**Pull request by ahorek**
fixes https://github.com/fny/xorcist/issues/11

### CODE REVIEW

File: lib/xorcist.rb [hunk 1]
```diff
@@ -1,8 +1,13 @@
...
 
 if RUBY_ENGINE == 'jruby'
-  require 'java'
-  require File.expand_path('../xorcist.jar', __FILE__)
+  require 'jruby'
+  require 'xorcist.jar'
+  if JRuby.respond_to?(:load_ext)
+    JRuby::Util.load_ext('org.xorcist.jruby.XorcistLibrary')
+  else
+    org.xorcist.jruby.XorcistLibrary.new.load(JRuby.runtime, false) # jruby < 9.2
```
Comment (ahorek) [inline lib/xorcist.rb:9]: feel free to remove this part if you don't want to support (very old) jruby versions

File: Rakefile [hunk 2]
```diff
@@ -12,8 +12,7 @@ gemspec = Gem::Specification.load(File.expand_path('xorcist.gemspec',  __FILE__)
 if RUBY_ENGINE == 'jruby'
   require 'rake/javaextensiontask'
   Rake::JavaExtensionTask.new('xorcist', gemspec) do |ext|
-    ext.source_version = '1.6'
-    ext.target_version = '1.6'
+    ext.release = '8'
```
Comment (ahorek) [inline Rakefile:15]: this will probably break jruby on java < 8, but it's unlikely someone's still using such old versions
